### ISSUE TITLE
Republish with the zero padding changes on npm

### ISSUE THREAD

**Issue by seigneur** [michalbe/binascii#13]
Hi, if possible can you republish the zero padded version on npm, because the version from npm does not have those changes. (spend a day and a half debugging ) Thanks.

**Comment by touy** [comment]
same , here I think something wrong with them ....

**Comment by michalbe** [comment]
OMG, sry I didn't get notifications from this reposomehow. Yes, I'll publish it later today.

**Comment by michalbe** [comment]
Statistically someone will need this version published next April, but I just wanted to let you guys know this was published earlier this month.
